'use strict';

const fs = require('fs');
const path = require('path');

const { downloadRelease, ensureExecutable, releasesTagUrl } = require('./download');
const { PLATFORMS, detectPlatform } = require('./platforms');

const VERSION = require('../package.json').version;

function packageRoot(npmPackage) {
  const pkgJson = require.resolve(`${npmPackage}/package.json`);
  return path.dirname(pkgJson);
}

function listInstalledPlatformPackages() {
  const found = [];
  for (const platform of PLATFORMS) {
    try {
      found.push(platform.npmPackage);
      require.resolve(`${platform.npmPackage}/package.json`);
    } catch {
      found.pop();
    }
  }
  return found;
}

function materializeIfVirtual(binPath, platform) {
  const normalized = binPath.replace(/\\/g, '/');
  if (!normalized.includes('.zip/')) {
    return binPath;
  }
  const destDir = path.join(
    require('./download').cacheRoot(),
    VERSION,
    `${platform.key}-pnp`,
  );
  const dest = path.join(destDir, platform.binaryName);
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(destDir, { recursive: true });
    fs.copyFileSync(binPath, dest);
    ensureExecutable(dest);
  }
  return dest;
}

function resolveOptionalBinary(platform) {
  const binPath = path.join(packageRoot(platform.npmPackage), platform.binaryName);
  if (!fs.existsSync(binPath)) {
    throw Object.assign(
      new Error(
        `${platform.npmPackage} is installed but ${platform.binaryName} is missing`,
      ),
      { code: 'ASTROLABE_BINARY_MISSING' },
    );
  }
  return materializeIfVirtual(binPath, platform);
}

function envOverridePath() {
  const fromEnv = process.env.ASTROLABE_BINARY_PATH;
  if (!fromEnv) return null;
  if (!fs.existsSync(fromEnv)) {
    console.error(`[astrolabe] ignoring ASTROLABE_BINARY_PATH, file not found: ${fromEnv}`);
    return null;
  }
  return fromEnv;
}

async function resolveBinary() {
  const override = envOverridePath();
  if (override) return override;

  const platform = detectPlatform();

  try {
    const binPath = resolveOptionalBinary(platform);
    ensureExecutable(binPath);
    return binPath;
  } catch (error) {
    if (error && error.code !== 'MODULE_NOT_FOUND' && error.code !== 'ASTROLABE_BINARY_MISSING') {
      throw error;
    }
  }

  try {
    return await downloadRelease(platform, VERSION);
  } catch (downloadError) {
    const others = listInstalledPlatformPackages().filter(
      (name) => name !== platform.npmPackage,
    );
    const otherHint = others.length
      ? `\nFound platform package(s) for a different architecture: ${others.join(', ')}.\n` +
        `This usually means node_modules was copied across OS/arch, or the lockfile was generated by npm < 11 which can drop optionalDependencies.`
      : `\nCommon causes: npm/pnpm/yarn --omit=optional, --ignore-scripts, or a lockfile generated on another OS/arch (npm < 11 bug).`;

    throw new Error(
      `Could not locate ${platform.npmPackage} (needed on this machine) and GitHub Releases fallback failed: ${downloadError.message}` +
        otherHint +
        `\nTried: ${require('./download').cacheRoot()}/${VERSION}/${platform.key}/` +
        `\nReleases: ${releasesTagUrl(VERSION)}`,
    );
  }
}

module.exports = { resolveBinary };
