(library_import (import_specification (configurable_uri (uri (string_literal) @import))))
(library_import (import_specification (uri (string_literal) @import)))
(library_export (configurable_uri (uri (string_literal) @import)))
(part_directive (uri (string_literal) @import))
(part_of_directive (uri (string_literal) @import))
